// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-X0bo5Qzi-nHYxgvtg9htX6nEaguseHw',
    appId: '1:246695668756:web:43d71479fa41a1b8300b01',
    messagingSenderId: '246695668756',
    projectId: 'imnovacion',
    authDomain: 'imnovacion.firebaseapp.com',
    storageBucket: 'imnovacion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuy_VxxUiiAUpk6ScLaSPBOjCYk9G9tz0',
    appId: '1:246695668756:android:63196ebf6c3d3c9b300b01',
    messagingSenderId: '246695668756',
    projectId: 'imnovacion',
    storageBucket: 'imnovacion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnvOXfbQbq36ZeWPk5wHvhssK1VFZMUts',
    appId: '1:246695668756:ios:fc5995462227c838300b01',
    messagingSenderId: '246695668756',
    projectId: 'imnovacion',
    storageBucket: 'imnovacion.appspot.com',
    androidClientId: '246695668756-enm45ik87lbo58b3qe2uoh8eltq7e2nq.apps.googleusercontent.com',
    iosClientId: '246695668756-mok1pi6pkt4tf6lgu3bea06g4f2nfjbs.apps.googleusercontent.com',
    iosBundleId: 'com.imnovacion.app',
  );
}
